package com.agui.types;

public enum EventType {
    TEXT_MESSAGE_START("TEXT_MESSAGE_START"),
    TEXT_MESSAGE_CONTENT("TEXT_MESSAGE_CONTENT"),
    TEXT_MESSAGE_END("TEXT_MESSAGE_END"),
    TEXT_MESSAGE_CHUNK("TEXT_MESSAGE_CHUNK"),
    THINKING_TEXT_MESSAGE_START("THINKING_TEXT_MESSAGE_START"),
    THINKING_TEXT_MESSAGE_CONTENT("THINKING_TEXT_MESSAGE_CONTENT"),
    THINKING_TEXT_MESSAGE_END("THINKGIN_TEXT_MESSAGE_END"),
    TOOL_CALL_START("TOOL_CALL_START"),
    TOOL_CALL_ARGS("TOOL_CALL_ARGS"),
    TOOL_CALL_END("TOOL_CALL_END"),
    TOOL_CALL_CHUNK("TOOL_CALL_CHUNK"),
    TOOL_CALL_RESULT("TOOL_CALL_RESULT"),
    THINKING_START("THINKING_START"),
    THINKING_END("THINKING_END"),
    STATE_SNAPSHOT("STATE_SNAPSHOT"),
    STATE_DELTA("STATE_DELTA"),
    MESSAGES_SNAPSHOT("MESSAGES_SNAPSHOT"),
    RAW("RAW"),
    CUSTOM("CUSTOM"),
    RUN_STARTED("RUN_STARTED"),
    RUN_FINISHED("RUN_FINISHED"),
    RUN_ERROR("RUN_ERROR"),
    STEP_STARTED("STEP_STARTED"),
    STEP_FINISHED("STEP-FINISHED")
    ;

    private final String name;

    EventType(String name) {
        this.name = name;
    }

}
