---
title: Graph Diagram
---
flowchart TD
    __START__((start))
    __END__((stop))
    reception_agent("reception_agent")
    request_classifier("request_classifier")
    data_agent("data_agent")
    translation_agent("translation_agent")
    data_analysis_agent("data_analysis_agent")
    report_generator("report_generator")
    condition1{"check state"}
    __START__:::__START__ --> reception_agent:::reception_agent
    data_agent:::data_agent --> report_generator:::report_generator
    data_analysis_agent:::data_analysis_agent --> report_generator:::report_generator
    reception_agent:::reception_agent --> request_classifier:::request_classifier
    translation_agent:::translation_agent --> report_generator:::report_generator
    request_classifier:::request_classifier -.-> condition1:::condition1
    condition1:::condition1 -.->|default| data_agent:::data_agent
%%	request_classifier:::request_classifier -.->|default| data_agent:::data_agent
    condition1:::condition1 -.->|translation| translation_agent:::translation_agent
%%	request_classifier:::request_classifier -.->|translation| translation_agent:::translation_agent
    condition1:::condition1 -.->|data_analysis| data_analysis_agent:::data_analysis_agent
%%	request_classifier:::request_classifier -.->|data_analysis| data_analysis_agent:::data_analysis_agent
    condition1:::condition1 -.->|math| data_agent:::data_agent
%%	request_classifier:::request_classifier -.->|math| data_agent:::data_agent
    report_generator:::report_generator --> __END__:::__END__

    classDef ___START__ fill:black,stroke-width:1px,font-size:xx-small;
    classDef ___END__ fill:black,stroke-width:1px,font-size:xx-small;
