#app:
#  env: daily
#  regionId: cn-hangzhou
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript
    min-response-size: 2048

spring:
  ai:
    alibaba:
      studio:
        login-method: third_party
        upload-method: oss
        oss:
          endpoint: oss-ap-southeast-1.aliyuncs.com
          internal-endpoint: oss-ap-southeast-1.aliyuncs.com
          access-key-id: ${OSS_ACCESS_KEY_ID}
          access-key-secret: ${OSS_ACCESS_KEY_SECRET}
          bucket: agentscope-java-preview
    openai:
      base-url: ${OPENAI_BASE_URL}
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  application:
    name: saa-agui

